name: navigation
description: Application navigation layer
version: 0.0.1
publish_to: none
environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: 5.0.4
  home:
    path: ../features/home/
  card:
    path: ../features/card/
  settings:
    path: ../features/settings/
  order:
    path: ../features/order/
  core:
    path: ../core/
  dashboard:
    path: ../features/dashboard/
  onboarding:
    path: ../features/onboarding/
  auth:
    path: ../features/auth/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: 5.0.2
  build_runner: ^2.3.3

flutter:
