name: home
description: Home screen module.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ../../domain
  core:   
    path: ../../core
  data:   
    path: ../../data
  core_ui:   
    path: ../../core_ui

  #bloc
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  #base
  equatable: ^2.0.5
  cloud_firestore: ^4.8.1
  cached_network_image: ^3.2.3
  #animated text
  animated_text_kit: ^4.2.2
  flutter_spinkit: ^5.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
   


flutter:

