name: amazon_prime
description: Flutter

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  very_good_analysis: ^5.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  home:
    path: features/./home/
  core:
    path: ./core

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  #Native splash 
  flutter_native_splash: ^2.3.1
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/cofix_logo.png"
  color: "#000000"


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 200
          style: italic







  
