import 'package:core_ui/core_ui.dart';

final ThemeData myTheme = ThemeData(
  useMaterial3: true,
  brightness: Brightness.light,
  primaryColor: ApplicationColors.primaryColor,
  primaryColorLight: ApplicationColors.primaryColorLight,
  primaryColorDark: ApplicationColors.primaryColorDark,
  canvasColor: ApplicationColors.canvasColor,
  scaffoldBackgroundColor: ApplicationColors.scaffoldBackgroundColor,
  dividerColor: ApplicationColors.dividerColor,
  highlightColor: ApplicationColors.highlightColor,
  splashColor: ApplicationColors.splashColor,
  unselectedWidgetColor: ApplicationColors.unselectedWidgetColor,
  disabledColor: ApplicationColors.disabledColor,
  secondaryHeaderColor: ApplicationColors.secondaryHeaderColor,
  dialogBackgroundColor: ApplicationColors.disabledColor,
  indicatorColor: ApplicationColors.indicatorColor,
  hintColor: ApplicationColors.hintColor,
  buttonTheme: const ButtonThemeData(
    textTheme: ButtonTextTheme.normal,
    minWidth: Dimensions.SIZE_88,
    height: Dimensions.SIZE_36,
    padding: EdgeInsets.only(
        top: Dimensions.SIZE_0,
        bottom: Dimensions.SIZE_0,
        left: Dimensions.SIZE_16,
        right: Dimensions.SIZE_16),
    shape: RoundedRectangleBorder(
      side: BorderSide(
        color: ApplicationColors.primaryColor,
        width: Dimensions.SIZE_0,
        style: BorderStyle.none,
      ),
      borderRadius: BorderRadius.all(
        Radius.circular(Dimensions.SIZE_2),
      ),
    ),
    alignedDropdown: false,
    buttonColor: ApplicationColors.buttonColor,
    disabledColor: ApplicationColors.primaryColor,
    highlightColor: ApplicationColors.primaryColor,
    splashColor: ApplicationColors.primaryColor,
    focusColor: ApplicationColors.primaryColor,
    hoverColor: ApplicationColors.primaryColor,
    colorScheme: ColorScheme(
      primary: ApplicationColors.primaryColor,
      secondary: ApplicationColors.red,
      surface: ApplicationColors.white,
      background: ApplicationColors.primaryColorLight,
      error: ApplicationColors.red,
      onPrimary: ApplicationColors.white,
      onSecondary: ApplicationColors.white,
      onSurface: ApplicationColors.primaryColor,
      onBackground: ApplicationColors.white,
      onError: ApplicationColors.white,
      brightness: Brightness.light,
    ),
  ),
);
