name: core
description: Core Module.
version: 0.0.1
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  #firebase
  cloud_firestore: ^4.8.1
  firebase_core: ^2.14.0
  #dependecy injection
  get_it: ^7.6.0
  #base
  equatable: ^2.0.5
  #bloc
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  #locale storage
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  #connection
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
