name: core
description: Core Module.
version: 0.0.1
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.8.1
  flutter:
    sdk: flutter

  #dependecy injection
  get_it: ^7.6.0
  #base
  equatable: ^2.0.5

  domain:
    path: ../domain
  data:
    path: ../data
  home:
    path: ../features/./home    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

