export 'package:amazon_prime/src/app/cofix.dart';
export 'package:core/core.dart';
export 'package:core/di/firebase_options.dart';
export 'package:core_ui/core_ui.dart';
export 'package:flutter/material.dart';
export 'package:home/src/home.dart';
export 'package:navigation/navigation.dart';
export 'package:product_details/product_details.dart';
export 'package:settings/settings.dart';
