name: core_ui
description: A new Flutter package project.
version: 0.0.1
publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core/

  #Fonts
  google_fonts: ^4.0.4
  #cahce image
  cached_network_image: ^3.2.3
  #loading widget
  flutter_spinkit: ^5.2.0
  #animated text
  animated_text_kit: ^4.2.2
  #rating bar
  flutter_rating_bar: ^4.0.1
  #svg
  flutter_svg: ^2.0.7
  #lottie
  lottie: ^2.4.0
  #slidable
  flutter_slidable: ^3.0.0
  #snackBar
  awesome_snackbar_content: ^0.1.3
  #refresh screen
  liquid_pull_to_refresh: ^3.0.1
  #toast
  fluttertoast: ^8.2.2
  #Smooth page indicator:
  smooth_page_indicator: ^1.1.0
  #corusel slider
  carousel_slider: ^4.2.1
  #chart
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
